services:
  postgres:
    image: postgres:16.11-alpine
    container_name: lab-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - labnet

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: lab-minio
    command: server /data --console-address ":9001"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    networks:
      - labnet

  minio-init:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    container_name: lab-minio-init
    depends_on:
      - minio
    environment:
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    entrypoint: >
      /bin/sh -c "
      until mc alias set local $$MINIO_ENDPOINT $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD; do
        echo 'waiting minio...'; sleep 2;
      done;
      mc mb -p local/raw;
      mc mb -p local/bronze;
      mc mb -p local/silver;
      mc mb -p local/gold;
      echo 'buckets ready';
      "
    restart: "no"
    networks:
      - labnet

  pgadmin:
    image: dpage/pgadmin4:9.11.0
    container_name: lab-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "127.0.0.1:5050:80"
      - "[::1]:5050:80"

    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - labnet

volumes:
  pg_data:
  minio_data:
  pgadmin_data:

networks:
  labnet:
    name: labnet
